config/routes.rb
Rails.application.routes.draw do
  resources :messages do
    collection do
      get 'export_to_db'
    end
  end
  
  root 'messages#new'

end

app/models/message.rb
require 'csv'

class Message < ActiveRecord::Base
  validates :name, :email, :subject, :content, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, 
                    allow_blank: true
                    
  belongs_to :submitter
  
  class << self
    def import!
      Thread.new do
        CSV.foreach(import_file, :headers => true) do |row|
          create(row.to_hash) do |m|
            m.submitter = Submitter.where(email: m.email).first_or_create
          end
        end
        ActiveRecord::Base.connection.close
      end
    end
    
    def add_to_csv(object)
      return false if object.invalid?
      CSV.open(import_file, "a+") do |csv|
        csv << object.attributes.values_at(*column_names)
      end
    end
  
    def import_file
      CSV.open(file_path, "a+"){|csv| csv << column_names} unless File.exist?(file_path)
      file_path
    end
    
    def file_path
      Rails.application.config.csv_file
    end
  end
end

app/models/submitter.rb
class Submitter < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
                    uniqueness: true, 
                    allow_blank: true
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if Message.add_to_csv(@message)
        format.html { redirect_to root_url, notice: 'Message was successfully sent!' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
    end
  end

  def export_to_db
    Message.import!
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Messages importing in process. Please refresh page in few minutes.' }
    end
  end
  
  protected
  
  def message_params
    params.require(:message).permit(:name, :email, :subject, :content)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8" 
      meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" 
        meta content="width=device-width, initial-scale=1.0" name="viewport" 
          title= content_for?(:title) ? yield(:title) : "Commpeak Test"
          = csrf_meta_tags
          /! Le HTML5 shim, for IE6-8 support of HTML elements
          /![if lt IE 9]
            | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script
          = stylesheet_link_tag "application", :media => "all"
          /! For third-generation iPad with high-resolution Retina display:
          /! Size should be 144 x 144 pixels
          = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
          /! For iPhone with high-resolution Retina display:
          /! Size should be 114 x 114 pixels
          = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
          /! For first- and second-generation iPad:
          /! Size should be 72 x 72 pixels
          = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
          /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
          /! Size should be 57 x 57 pixels
          = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
          /! For all other devices
          /! Size should be 32 x 32 pixels
          = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
          = javascript_include_tag "application"
  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button" 
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#"  
          = image_tag 'logo.png', alt: 'Commpeak', height: '30px' 
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to "New Message", root_path
          ul.nav.navbar-nav
            li= link_to "All Messages", messages_path
          ul.nav.navbar-nav
            li= link_to "Export data!", export_to_db_messages_path
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Main", "/"
          /! /.well
        /! /span
      /! /row
      br
        br
          footer
            p &copy; Company 2014
    /! /container

app/views/messages/index.html.slim
- model_class = Message
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:subject)
      th= model_class.human_attribute_name(:content)
      th= t '.actions', :default => t("helpers.actions")
  tbody
    - @messages.each do |message|
      tr
        td= message.id
        td= message.name
        td= message.email
        td= message.subject
        td= message.content
        td
          = link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(message), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/messages/new.html.slim
h1 New message
br
br
= form_for @message, html: {class: "form-horizontal message", role: "form"} do |f|
  - if @message.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        h3.panel-title
          = pluralize(@message.errors.count, "error")
          | prohibited this message from being saved:
      .panel-body
        ul
          - @message.errors.full_messages.each do |msg|
            li= msg
            
  .control-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', placeholder: "Enter name"
  .control-group
    = f.label :email, class: 'control-label'
    .controls
      = f.text_field :email, class: 'form-control', placeholder: "Enter email"
  .control-group
    = f.label :subject, class: 'control-label'
    .controls
      = f.text_field :subject, class: 'form-control', placeholder: "Enter subject"
  .control-group
    = f.label :content, class: 'control-label'
    .controls
      = f.text_area :content, class: 'form-control', placeholder: "Enter content"
  br
  .control-group
    .controls
      button.btn.btn-default class = "form-control btn-info" type="submit"  Send